<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="IUnitOfWork\**" />
    <Compile Remove="UnitOfWork\**" />
    <EmbeddedResource Remove="IUnitOfWork\**" />
    <EmbeddedResource Remove="UnitOfWork\**" />
    <None Remove="IUnitOfWork\**" />
    <None Remove="UnitOfWork\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Repository\Repository.csproj" />
  </ItemGroup>

</Project>
